import { sources } from './sources';
export type GlossarySource = { title: string; url: string };
export const glossarySources: Record<string, GlossarySource> = {
  ...Object.fromEntries(
    sources.map((s) => [
      'p' + s.id,
      { title: s.author + ' · ' + s.title, url: s.url },
    ]),
  ),
  fundamentals: {
    title: 'Google · ML Fundamentals Glossary',
    url: 'https://developers.google.com/machine-learning/glossary/fundamentals',
  },
  intro: {
    title: 'Google · What is Machine Learning?',
    url: 'https://developers.google.com/machine-learning/intro-to-ml/what-is-ml',
  },
  supervised: {
    title: 'Google · Supervised Learning',
    url: 'https://developers.google.com/machine-learning/intro-to-ml/supervised',
  },
  split: {
    title: 'Google · Dividing the original dataset',
    url: 'https://developers.google.com/machine-learning/crash-course/overfitting/dividing-datasets',
  },
  overfit: {
    title: 'Google · Overfitting',
    url: 'https://developers.google.com/machine-learning/crash-course/overfitting/overfitting',
  },
  loss: {
    title: 'Google · Linear regression: Loss',
    url: 'https://developers.google.com/machine-learning/crash-course/linear-regression/loss',
  },
  gradient: {
    title: 'Google · Gradient descent',
    url: 'https://developers.google.com/machine-learning/crash-course/linear-regression/gradient-descent',
  },
  neural: {
    title: 'Google · Neural networks',
    url: 'https://developers.google.com/machine-learning/crash-course/neural-networks',
  },
  embedding: {
    title: 'Google · Embeddings',
    url: 'https://developers.google.com/machine-learning/crash-course/embeddings',
  },
  tree: {
    title: 'scikit-learn · Decision Trees',
    url: 'https://scikit-learn.org/stable/modules/tree.html',
  },
  ensemble: {
    title: 'scikit-learn · Ensembles',
    url: 'https://scikit-learn.org/stable/modules/ensemble.html',
  },
  leakage: {
    title: 'scikit-learn · Common pitfalls',
    url: 'https://scikit-learn.org/stable/common_pitfalls.html',
  },
  xgboost: {
    title: 'Chen & Guestrin · XGBoost (2016)',
    url: 'https://arxiv.org/abs/1603.02754',
  },
  transformer: {
    title: 'Vaswani et al. · Attention Is All You Need (2017)',
    url: 'https://arxiv.org/abs/1706.03762',
  },
  hftransformer: {
    title: 'Hugging Face · How do Transformers work?',
    url: 'https://huggingface.co/learn/llm-course/chapter1/4',
  },
  tokenizer: {
    title: 'Hugging Face · Tokenizers',
    url: 'https://huggingface.co/learn/llm-course/en/chapter2/4',
  },
  llm: {
    title: 'Google · Introduction to Large Language Models',
    url: 'https://developers.google.com/machine-learning/crash-course/llm',
  },
  tuning: {
    title: 'Google · Fine-tuning, distillation, and prompt engineering',
    url: 'https://developers.google.com/machine-learning/crash-course/llm/tuning',
  },
  generation: {
    title: 'Hugging Face · Generation strategies',
    url: 'https://huggingface.co/docs/transformers/en/generation_strategies',
  },
  foundation: {
    title: 'Bommasani et al. · Foundation Models (2021)',
    url: 'https://arxiv.org/abs/2108.07258',
  },
  rag: {
    title: 'Lewis et al. · Retrieval-Augmented Generation (2020)',
    url: 'https://arxiv.org/abs/2005.11401',
  },
  rlhf: {
    title: 'Ouyang et al. · Learning from human feedback (2022)',
    url: 'https://arxiv.org/abs/2203.02155',
  },
  lora: {
    title: 'Hu et al. · LoRA (2021)',
    url: 'https://arxiv.org/abs/2106.09685',
  },
  cot: {
    title: 'Wei et al. · Chain-of-Thought Prompting (2022)',
    url: 'https://arxiv.org/abs/2201.11903',
  },
  hallucination: {
    title: 'Ji et al. · Survey of Hallucination in NLG',
    url: 'https://arxiv.org/abs/2202.03629',
  },
  pdp: {
    title: 'scikit-learn · Partial dependence and ICE',
    url: 'https://scikit-learn.org/stable/modules/partial_dependence.html',
  },
  permutation: {
    title: 'scikit-learn · Permutation feature importance',
    url: 'https://scikit-learn.org/stable/modules/permutation_importance.html',
  },
  metrics: {
    title: 'Google · Accuracy, recall, precision and related metrics',
    url: 'https://developers.google.com/machine-learning/crash-course/classification/accuracy-precision-recall',
  },
  scoring: {
    title: 'scikit-learn · Metrics and scoring',
    url: 'https://scikit-learn.org/stable/modules/model_evaluation.html',
  },
  crossvalidation: {
    title: 'scikit-learn · Cross-validation',
    url: 'https://scikit-learn.org/stable/modules/cross_validation.html',
  },
  calibration: {
    title: 'Guo et al. · On Calibration of Modern Neural Networks (2017)',
    url: 'https://proceedings.mlr.press/v70/guo17a.html',
  },
  uncertainty: {
    title: 'Kendall & Gal · What Uncertainties Do We Need? (2017)',
    url: 'https://arxiv.org/abs/1703.04977',
  },
  kendall: {
    title: 'SciPy · Kendall’s tau',
    url: 'https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html',
  },
  rbo: {
    title:
      'Webber et al. · A Similarity Measure for Indefinite Rankings (2010)',
    url: 'https://codalism.com/research/papers/wmz10_tois.pdf',
  },
  mlops: {
    title: 'Google Cloud · MLOps: Continuous delivery and automation pipelines',
    url: 'https://docs.cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning',
  },
  monitoring: {
    title: 'Google · Production ML systems: Monitoring pipelines',
    url: 'https://developers.google.com/machine-learning/crash-course/production-ml-systems/monitoring',
  },
  drift: {
    title: 'Google Cloud · Introduction to Model Monitoring',
    url: 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/machine-learning/model-monitoring/overview',
  },
  tracking: {
    title: 'MLflow · Experiment Tracking',
    url: 'https://mlflow.org/docs/latest/ml/tracking/',
  },
  registry: {
    title: 'MLflow · Model Registry',
    url: 'https://mlflow.org/docs/latest/ml/model-registry/',
  },
  modelcard: {
    title: 'Mitchell et al. · Model Cards for Model Reporting (2019)',
    url: 'https://arxiv.org/abs/1810.03993',
  },
  datasheet: {
    title: 'Gebru et al. · Datasheets for Datasets',
    url: 'https://arxiv.org/abs/1803.09010',
  },
  hai: {
    title: 'Amershi et al. · Guidelines for Human-AI Interaction (2019)',
    url: 'https://www.microsoft.com/en-us/research/publication/guidelines-for-human-ai-interaction/',
  },
  tlx: {
    title: 'NASA · Task Load Index',
    url: 'https://www.nasa.gov/human-systems-integration-division/nasa-task-load-index-tlx/',
  },
};
export type Term = {
  id: string;
  zh: string;
  en: string;
  definition: string;
  source: string;
  related: string[];
  note?: string;
};
const t = (
  id: string,
  zh: string,
  en: string,
  definition: string,
  source: string,
  related: string[] = [],
  note?: string,
): Term => ({ id, zh, en, definition, source, related, note });
export const glossaryGroups = [
  {
    id: 'basics',
    zh: '先认识 AI',
    en: 'AI & learning',
    intro: '先分清研究领域、学习方式与任务类型。',
    terms: [
      t(
        'ai',
        '人工智能',
        'Artificial Intelligence · AI',
        '让计算系统完成感知、语言、推理或决策等任务的广泛领域；机器学习是其中一个分支。',
        'fundamentals',
        ['ml', 'llm', 'xai'],
      ),
      t(
        'ml',
        '机器学习',
        'Machine Learning · ML',
        '利用数据学习规律，使模型能够预测或生成输出的方法。',
        'intro',
        ['model', 'training', 'inference'],
      ),
      t(
        'deep-learning',
        '深度学习',
        'Deep Learning · DL',
        '使用多层神经网络学习数据表示与输入输出关系的一类机器学习方法。',
        'neural',
        ['neural-network', 'transformer'],
      ),
      t(
        'generative-ai',
        '生成式人工智能',
        'Generative AI',
        '学习数据模式并生成文本、图像、声音等内容的模型与系统。',
        'intro',
        ['llm', 'foundation-model'],
      ),
      t(
        'supervised',
        '监督学习',
        'Supervised Learning',
        '利用带目标标签的样本，学习从输入到目标输出的关系。',
        'intro',
        ['label', 'classification', 'regression'],
        '自拟例：用记录了“抓取成功／失败”的传感器数据学习失败预测。',
      ),
      t(
        'unsupervised',
        '无监督学习',
        'Unsupervised Learning',
        '在没有指定目标标签的数据中寻找结构或模式。',
        'intro',
        ['clustering', 'supervised'],
        '自拟例：按振动模式把设备运行记录分成几组，再由工程师理解各组含义。',
      ),
      t(
        'self-supervised',
        '自监督学习',
        'Self-supervised Learning',
        '从数据自身构造训练目标，例如用一段文字预测被遮住的词或下一个词元。',
        'hftransformer',
        ['pretraining', 'supervised'],
        '“没有逐条人工标注”仍然可以有明确的训练目标。',
      ),
      t(
        'reinforcement-learning',
        '强化学习',
        'Reinforcement Learning · RL',
        '智能体与环境交互，根据奖励信号学习行动策略，以提高累积回报。',
        'intro',
        ['policy', 'rlhf'],
      ),
      t(
        'policy',
        '策略',
        'Policy',
        '强化学习中，决定在某种状态下采取什么行动的规则或概率分布。',
        'fundamentals',
        ['reinforcement-learning'],
      ),
      t(
        'classification',
        '分类',
        'Classification',
        '预测样本属于哪个类别，或给出各类别的预测分数。',
        'intro',
        ['regression', 'precision'],
        '自拟例：“正常／故障”是分类；“还可运行多少小时”是回归。',
      ),
      t(
        'regression',
        '回归',
        'Regression',
        '预测数值的任务，例如温度、载荷或预计使用寿命。',
        'intro',
        ['classification', 'rmse'],
      ),
      t(
        'clustering',
        '聚类',
        'Clustering',
        '按相似性把样本组织成组；类别通常不是训练前指定的标签。',
        'intro',
        ['unsupervised'],
      ),
      t(
        'transfer-learning',
        '迁移学习',
        'Transfer Learning',
        '把从一个任务或数据中学到的表示用于另一个任务，减少从零学习的需要。',
        'hftransformer',
        ['pretraining', 'fine-tuning'],
      ),
      t(
        'foundation-model',
        '基础模型',
        'Foundation Model',
        '在广泛数据上训练、可以适配多种下游任务的模型。',
        'foundation',
        ['llm', 'fine-tuning'],
        '“基础模型”强调可适配的角色；“大语言模型”强调语言建模，两者不是完全相同的分类。',
      ),
    ],
  },
  {
    id: 'data',
    zh: '数据与训练',
    en: 'Data & training',
    intro: '读方法章节时，先找输入、标签、训练方式和验证数据。',
    terms: [
      t(
        'dataset',
        '数据集',
        'Dataset',
        '为训练、评估或分析组织的一组数据样本。',
        'supervised',
        ['sample', 'dataset-split'],
      ),
      t(
        'sample',
        '样本',
        'Sample / Example / Instance',
        '模型处理的一条实例，例如一次抓取记录或一张图片。',
        'supervised',
        ['dataset', 'feature'],
      ),
      t(
        'feature',
        '特征',
        'Feature',
        '输入中供模型使用的属性或表示，例如温度、速度或从图像学到的表示。',
        'supervised',
        ['label', 'attribution'],
      ),
      t(
        'label',
        '标签',
        'Label / Target',
        '学习或评估时作为目标的记录值，例如物种类别或测量到的能耗。',
        'supervised',
        ['supervised', 'prediction'],
      ),
      t(
        'ground-truth',
        '参考真值',
        'Ground Truth',
        '评估中作为答案依据的观测或标注；其可靠性取决于测量、标注与任务定义。',
        'monitoring',
        ['label', 'datasheet'],
      ),
      t(
        'model',
        '模型',
        'Model',
        '将输入映射到输出的计算结构及其参数；训练后可以对新样本产生预测。',
        'supervised',
        ['parameter', 'inference'],
      ),
      t(
        'training',
        '训练',
        'Training',
        '利用训练数据与目标调整模型，使它更好地完成任务的过程。',
        'supervised',
        ['loss', 'inference'],
      ),
      t(
        'inference',
        '推理／推断',
        'Inference',
        '用模型处理输入并产生预测或生成结果的过程。通常不意味着正在更新模型参数。',
        'supervised',
        ['training', 'reasoning'],
        '在工程文档里，inference 常指运行模型；reasoning 则通常谈问题求解中的推理能力。',
      ),
      t(
        'prediction',
        '预测',
        'Prediction',
        '模型对输入给出的输出，可以是类别、数值或概率分布。',
        'supervised',
        ['inference', 'explanation'],
      ),
      t(
        'parameter',
        '参数',
        'Parameter / Weight',
        '模型中从训练中学习或调整的数值；神经网络权重是常见例子。',
        'gradient',
        ['hyperparameter', 'feature'],
      ),
      t(
        'hyperparameter',
        '超参数',
        'Hyperparameter',
        '控制模型或训练过程的设置，例如学习率和树的最大深度。',
        'fundamentals',
        ['parameter', 'learning-rate'],
        '特征是输入；参数是模型学到的值；超参数是训练和模型设计中的设置。',
      ),
      t(
        'loss',
        '损失函数',
        'Loss function',
        '把预测与训练目标之间的差异转成优化信号的函数。',
        'loss',
        ['gradient-descent', 'rmse'],
      ),
      t(
        'gradient-descent',
        '梯度下降',
        'Gradient descent',
        '根据损失对参数的变化方向，反复小步更新参数，以降低损失的优化方法。',
        'gradient',
        ['learning-rate', 'backpropagation'],
      ),
      t(
        'learning-rate',
        '学习率',
        'Learning rate',
        '控制一次参数更新步长的训练设置。',
        'gradient',
        ['gradient-descent', 'hyperparameter'],
      ),
      t(
        'batch-epoch',
        '批次与轮次',
        'Batch / Epoch',
        'Batch 是一次处理的一组样本；Epoch 是训练过程遍历完整训练集一遍。',
        'fundamentals',
        ['training'],
      ),
      t(
        'dataset-split',
        '训练／验证／测试集',
        'Training / Validation / Test split',
        '训练集用于学习，验证集用于选择方案和调参，测试集用于最终评估未见数据表现。',
        'split',
        ['cross-validation', 'data-leakage'],
        '同一人的相近记录或相邻时间片是否跨集合，要结合研究目标决定，避免无意泄漏。',
      ),
      t(
        'overfitting',
        '过拟合',
        'Overfitting',
        '模型过度贴合训练数据，因而在新数据上的表现变差。',
        'overfit',
        ['generalization', 'regularization'],
      ),
      t(
        'underfitting',
        '欠拟合',
        'Underfitting',
        '模型还没有充分学到任务中的关系，连训练数据上的表现也不理想。',
        'overfit',
        ['overfitting'],
      ),
      t(
        'generalization',
        '泛化',
        'Generalization',
        '模型把学到的规律用于未见样本的能力。',
        'overfit',
        ['dataset-split', 'data-drift'],
      ),
      t(
        'regularization',
        '正则化',
        'Regularization',
        '约束模型复杂度或训练过程、帮助减少过拟合的一类方法。',
        'fundamentals',
        ['overfitting'],
      ),
      t(
        'data-leakage',
        '数据泄漏',
        'Data leakage',
        '训练或模型选择使用了预测时不应获得的信息，使评估看起来过于理想。',
        'leakage',
        ['dataset-split', 'training-serving-skew'],
        '自拟例：用“维修后更换的部件”预测“维修前是否故障”，就可能提前泄露答案。',
      ),
    ],
  },
  {
    id: 'models',
    zh: '模型与表示',
    en: 'Models & representations',
    intro: '模型负责预测；解释方法则帮助分析预测是怎样形成的。',
    terms: [
      t(
        'decision-tree',
        '决策树',
        'Decision tree',
        '通过一系列特征条件分裂输入空间，在叶节点给出预测的模型。',
        'tree',
        ['random-forest', 'treeinterpreter'],
      ),
      t(
        'random-forest',
        '随机森林',
        'Random forest',
        '将多棵带随机性的决策树组合起来，对分类结果投票或对数值预测取平均。',
        'ensemble',
        ['decision-tree', 'treeshap'],
      ),
      t(
        'ensemble',
        '集成学习',
        'Ensemble learning',
        '把多个模型组合成一个预测系统的方式。随机森林和梯度提升是不同的集成路线。',
        'ensemble',
        ['random-forest', 'boosting'],
      ),
      t(
        'boosting',
        '梯度提升',
        'Gradient boosting',
        '逐步添加模型，让后续模型改进当前整体预测的一类方法；常以树为基本模型。',
        'ensemble',
        ['xgboost'],
      ),
      t(
        'xgboost',
        '极端梯度提升工具',
        'XGBoost',
        '面向梯度提升的高效学习系统，常用于表格数据预测；它是建模工具，不是 XAI 解释器。',
        'xgboost',
        ['boosting', 'treeshap'],
      ),
      t(
        'neural-network',
        '神经网络',
        'Neural network',
        '由相互连接的计算层组成，通过参数与非线性变换学习输入输出关系的模型。',
        'neural',
        ['deep-learning', 'activation'],
      ),
      t(
        'activation',
        '激活函数',
        'Activation function',
        '作用于计算单元输出的函数；非线性激活帮助网络表达复杂关系。',
        'neural',
        ['neural-network'],
      ),
      t(
        'backpropagation',
        '反向传播',
        'Backpropagation',
        '沿计算过程反向计算损失对各参数梯度的方法，常与梯度下降配合训练网络。',
        'fundamentals',
        ['gradient-descent'],
      ),
      t(
        'embedding',
        '嵌入／向量表示',
        'Embedding',
        '用数值向量表示对象，使某些任务相关的关系能在向量空间中表达。',
        'embedding',
        ['token', 'rag'],
        '自拟例：把材料描述变成向量后，可以按表示的相似性检索，而不只匹配原词。',
      ),
      t(
        'surrogate-model',
        '代理模型',
        'Surrogate model',
        '用于近似另一个复杂模型或昂贵过程的模型。LIME 使用局部解释代理；工程案例用代理近似仿真。',
        'p25',
        ['lime', 'model'],
        '两者都叫 surrogate，但用途与需要验证的误差不同。',
      ),
    ],
  },
  {
    id: 'language',
    zh: 'LLM 与生成式系统',
    en: 'Language models & generation',
    intro: '从词元与上下文，到微调、检索和生成。',
    terms: [
      t(
        'llm',
        '大语言模型',
        'Large Language Model · LLM',
        '以大规模语言数据训练的模型，学习词元序列的统计关系，可用于生成、理解和转换语言。',
        'llm',
        ['token', 'transformer', 'foundation-model'],
      ),
      t(
        'token',
        '词元',
        'Token',
        '语言模型处理的离散单位，可以是词、子词或字符；它不总与一个汉字或英文单词一一对应。',
        'tokenizer',
        ['tokenizer', 'context'],
      ),
      t(
        'tokenizer',
        '分词器',
        'Tokenizer',
        '把文本转成词元及其编号，并能把编号序列还原成文本的组件。',
        'tokenizer',
        ['token'],
      ),
      t(
        'context',
        '上下文',
        'Context / Context window',
        'Context 是当前预测可利用的输入信息；context window 指一次处理可容纳的上下文范围，通常以词元计。',
        'llm',
        ['token', 'rag'],
        '聊天历史、检索材料和指令都可能占用上下文；具体范围取决于模型及系统设置。',
      ),
      t(
        'transformer',
        'Transformer 架构',
        'Transformer',
        '以注意力机制组织序列信息的一种神经网络架构，是许多语言模型的基础。',
        'transformer',
        ['attention', 'encoder-decoder'],
      ),
      t(
        'attention',
        '注意力机制',
        'Attention / Self-attention',
        '计算不同位置的表示对当前表示有多大作用，并据此加权整合信息；self-attention 在同一序列内进行。',
        'transformer',
        ['transformer', 'attribution'],
        '这里的“注意力”是计算机制；拿它解释用户关心的模型依据，还需要另行论证。',
      ),
      t(
        'encoder-decoder',
        '编码器与解码器',
        'Encoder / Decoder',
        '编码器将输入转成表示；解码器利用表示和已有输出生成序列。Transformer 模型可采用不同的组合结构。',
        'hftransformer',
        ['transformer'],
      ),
      t(
        'pretraining',
        '预训练',
        'Pretraining',
        '先在较广泛的数据上训练模型，获得可供后续任务使用的能力与表示。',
        'hftransformer',
        ['fine-tuning', 'self-supervised'],
      ),
      t(
        'fine-tuning',
        '微调',
        'Fine-tuning',
        '在预训练模型基础上继续训练参数，使其更适合特定任务、领域或行为要求。',
        'tuning',
        ['pretraining', 'prompt', 'lora'],
      ),
      t(
        'prompt',
        '提示词／提示输入',
        'Prompt / Prompt engineering',
        'Prompt 是给模型的任务输入；prompt engineering 是组织指令、上下文和示例以引导输出的做法。',
        'tuning',
        ['fine-tuning', 'few-shot'],
        '修改提示通常发生在使用阶段；微调则涉及训练参数。',
      ),
      t(
        'few-shot',
        '少样本提示',
        'Few-shot prompting',
        '在提示中给出少量示范，让模型按示范处理新任务。Zero-shot 则不提供这类任务示范。',
        'tuning',
        ['prompt'],
      ),
      t(
        'distillation',
        '知识蒸馏',
        'Knowledge distillation',
        '利用较大或较强模型的输出等信息训练另一个模型，常用于获得更小、更高效的模型。',
        'tuning',
        ['fine-tuning'],
      ),
      t(
        'sft',
        '监督微调',
        'Supervised Fine-tuning · SFT',
        '用任务示范的输入—输出样本继续训练模型，例如用指令及高质量回答训练指令跟随。',
        'rlhf',
        ['fine-tuning', 'rlhf'],
      ),
      t(
        'rlhf',
        '人类反馈强化学习',
        'Reinforcement Learning from Human Feedback · RLHF',
        '利用人的偏好或反馈形成奖励信号，再用强化学习调整模型行为的一类训练流程。',
        'rlhf',
        ['sft', 'reinforcement-learning'],
        '人的偏好提供一种优化信号，并不自动保证所有回答都准确。',
      ),
      t(
        'lora',
        '低秩适配',
        'Low-Rank Adaptation · LoRA',
        '冻结原有模型权重，训练少量低秩更新矩阵的参数高效适配方法。',
        'lora',
        ['fine-tuning', 'parameter'],
      ),
      t(
        'rag',
        '检索增强生成',
        'Retrieval-Augmented Generation · RAG',
        '先检索与问题相关的外部材料，再把材料用于生成回答的系统方式。',
        'rag',
        ['embedding', 'context', 'fine-tuning'],
        '自拟例：先查产品维修手册，再依据检索段落回答。检索质量和回答是否忠于材料都值得检查。',
      ),
      t(
        'decoding',
        '解码／生成策略',
        'Decoding / Sampling',
        '把模型给出的词元概率转成实际输出序列的规则；可以选择最高分项，也可以进行采样。',
        'generation',
        ['temperature', 'top-p'],
      ),
      t(
        'temperature',
        '温度参数',
        'Temperature',
        '调节生成时概率分布尖锐程度的参数。采样时较低值通常更集中于高概率候选。',
        'generation',
        ['decoding'],
        '它控制采样行为，不能直接当作答案准确度的开关。',
      ),
      t(
        'top-p',
        '核采样',
        'Top-p / Nucleus sampling',
        '从累计概率达到设定阈值的候选集合中采样下一词元的策略。',
        'generation',
        ['decoding', 'temperature'],
      ),
      t(
        'hallucination',
        '幻觉',
        'Hallucination',
        '生成内容与依据、输入或可核实事实不一致的现象；具体判定依赖任务和所采用的定义。',
        'hallucination',
        ['rag', 'faithfulness'],
      ),
      t(
        'chain-of-thought',
        '思维链',
        'Chain of Thought · CoT',
        '通过中间文字步骤展开问题求解的提示或生成方式。',
        'cot',
        ['reasoning', 'faithfulness'],
        '中间文字有助于呈现解题步骤；其是否反映实际起作用的模型依据，是另一个研究问题。',
      ),
      t(
        'reasoning',
        '推理能力／问题求解',
        'Reasoning',
        '在 LLM 讨论中，通常指多步组织信息、得出结论或完成复杂问题求解的能力与过程。',
        'cot',
        ['inference', 'chain-of-thought'],
      ),
    ],
  },
  {
    id: 'explainability',
    zh: 'XAI 与解释方法',
    en: 'Explainability & methods',
    intro: '把研究对象、解释范围和方法名称分开看。',
    terms: [
      t(
        'xai',
        '可解释人工智能',
        'Explainable AI · XAI',
        '研究和设计让人理解 AI 行为与依据的方法、系统及交互。',
        'p1',
        ['interpretability', 'explanation'],
      ),
      t(
        'interpretability',
        '可解释性／可理解性',
        'Interpretability / Explainability',
        '不同论文对两词的用法并不完全相同：常分别强调模型可被理解的程度，以及提供解释的能力。阅读时以作者定义为准。',
        'p1',
        ['intrinsic-posthoc'],
      ),
      t(
        'explanation',
        '解释',
        'Explanation',
        '面向某个接收者的问题，选择并组织与系统行为相关的信息。',
        'p2',
        ['contrastive', 'explanation-needs'],
      ),
      t(
        'intrinsic-posthoc',
        '内在与事后解释',
        'Intrinsic / Post-hoc',
        '内在可解释依靠模型自身可检查的结构；事后解释则分析已经训练好的模型或输出。',
        'p1',
        ['decision-tree', 'shap'],
      ),
      t(
        'local-global',
        '局部与全局解释',
        'Local / Global explanation',
        '局部关注一个案例；全局关注模型在更大范围内的行为规律。',
        'p1',
        ['lime', 'pdp'],
      ),
      t(
        'agnostic-specific',
        '模型无关与模型特定',
        'Model-agnostic / Model-specific',
        '前者不依赖某一种模型内部结构；后者利用树结构、梯度等特定信息。',
        'p4',
        ['lime', 'treeshap'],
      ),
      t(
        'attribution',
        '特征归因',
        'Feature attribution',
        '把输出相对参考的变化或相关影响，分配给输入特征的分析方式。不同方法的分配含义不同。',
        'p6',
        ['shap', 'treeinterpreter', 'baseline'],
      ),
      t(
        'baseline',
        '基准／参考值',
        'Baseline / Reference value',
        '解释中用来比较的起点。SHAP 的基准依赖参考设定；实验中的 baseline 也可能指比较模型或条件。',
        'p6',
        ['attribution', 'treeinterpreter'],
      ),
      t(
        'shap',
        'SHAP 归因框架',
        'SHapley Additive exPlanations · SHAP',
        '基于 Shapley 思想，把预测相对参考的差异分配给特征的一类加性归因框架。',
        'p6',
        ['treeshap', 'attribution'],
      ),
      t(
        'treeshap',
        '树模型 SHAP',
        'TreeSHAP',
        '利用树结构高效计算 SHAP 归因的方法。',
        'p26',
        ['shap', 'treeinterpreter'],
      ),
      t(
        'treeinterpreter',
        '树路径解释器',
        'TreeInterpreter',
        '对支持的 sklearn 树模型沿决策路径分解预测：基准加各特征贡献等于预测。',
        'p23',
        ['treeshap', 'decision-tree'],
        '它累积路径上的节点预测变化；TreeSHAP 使用不同的归因原则。',
      ),
      t(
        'lime',
        '局部可解释代理',
        'Local Interpretable Model-agnostic Explanations · LIME',
        '在目标样本附近扰动输入，以简单代理模型近似原模型的局部行为。',
        'p7',
        ['surrogate-model', 'local-global'],
      ),
      t(
        'grad-cam',
        '梯度加权类激活映射',
        'Gradient-weighted Class Activation Mapping · Grad-CAM',
        '结合类别梯度与卷积特征图，生成与目标类别相关的粗粒度区域图。',
        'p21',
        ['saliency', 'sanity-check'],
      ),
      t(
        'saliency',
        '显著性图',
        'Saliency map',
        '用空间或输入位置上的分数显示模型对某个输出的相关敏感性或贡献的可视表示。',
        'p15',
        ['grad-cam', 'attribution'],
      ),
      t(
        'counterfactual',
        '反事实解释',
        'Counterfactual explanation',
        '给出一个改变后的输入，使模型得到不同或期望的结果。',
        'p8',
        ['dice', 'actionability'],
      ),
      t(
        'dice',
        '多样化反事实',
        'Diverse Counterfactual Explanations · DiCE',
        '生成多个彼此不同、同时接近当前案例的反事实方案的方法。',
        'p8',
        ['counterfactual'],
      ),
      t(
        'actionability',
        '可行动性',
        'Actionability',
        '解释或建议中的改变能否由相关的人在真实约束下实施。',
        'p8',
        ['counterfactual', 'agency'],
        '自拟例：“更换传感器位置”可能可操作，“改变已经发生的历史”通常不可操作。',
      ),
      t(
        'tcav',
        '概念激活向量测试',
        'Testing with Concept Activation Vectors · TCAV',
        '用概念示例定义方向，再测试模型对这些人可理解概念方向的敏感性。',
        'p9',
        ['concept-bottleneck'],
      ),
      t(
        'concept-bottleneck',
        '概念瓶颈模型',
        'Concept Bottleneck Model · CBM',
        '先预测可解释概念，再依据概念预测结果，形成可以检查或干预的中间层。',
        'p10',
        ['tcav', 'intervention'],
      ),
      t(
        'intervention',
        '干预',
        'Intervention',
        '有意改变模型输入、概念或内部变量，观察后续结果怎样变化的操作。',
        'p10',
        ['concept-bottleneck', 'mechanistic'],
      ),
      t(
        'pdp',
        '部分依赖图',
        'Partial Dependence Plot · PDP',
        '在选定特征取不同值时，对其他特征的样本分布求平均，显示模型平均预测变化。',
        'pdp',
        ['ice', 'local-global'],
      ),
      t(
        'ice',
        '个体条件期望曲线',
        'Individual Conditional Expectation · ICE',
        '对单个样本改变某个特征、保持其他输入不变，观察预测曲线。',
        'pdp',
        ['pdp'],
      ),
      t(
        'permutation-importance',
        '置换重要性',
        'Permutation feature importance',
        '打乱某特征后，观察模型评分下降多少，以衡量模型在给定数据上对它的依赖。',
        'permutation',
        ['attribution'],
        '强相关特征可能相互替代，读重要性时要留意。',
      ),
      t(
        'mechanistic',
        '机制可解释性',
        'Mechanistic interpretability',
        '研究模型内部哪些表示与计算过程共同形成输出，常结合结构分析与干预验证假设。',
        'p18',
        ['intervention', 'chain-of-thought'],
      ),
    ],
  },
  {
    id: 'evaluation',
    zh: '评估与研究证据',
    en: 'Evaluation & evidence',
    intro: '预测对不对、解释准不准、用户懂不懂，是相连但不同的评估问题。',
    terms: [
      t(
        'accuracy',
        '准确率',
        'Accuracy',
        '分类正确的样本数除以全部样本数。',
        'metrics',
        ['precision', 'recall'],
        '自拟例：100 次里判断对 90 次，准确率为 90%；类别不平衡时还需看其他指标。',
      ),
      t(
        'precision',
        '精确率／查准率',
        'Precision',
        '被模型判为正例的样本中，实际为正例的比例：TP / (TP + FP)。',
        'metrics',
        ['recall', 'accuracy'],
      ),
      t(
        'recall',
        '召回率／查全率',
        'Recall',
        '实际正例中，被模型正确找出的比例：TP / (TP + FN)。',
        'metrics',
        ['precision'],
      ),
      t(
        'f1',
        'F1 分数',
        'F1 score',
        '精确率与召回率的调和平均，用于综合观察二者：2PR / (P + R)。',
        'metrics',
        ['precision', 'recall'],
      ),
      t(
        'confusion-matrix',
        '混淆矩阵',
        'Confusion matrix',
        '按真实类别与预测类别排列计数，显示正确分类以及错分到哪里。',
        'scoring',
        ['false-positive'],
      ),
      t(
        'false-positive',
        '误报与漏报',
        'False positive / False negative',
        '误报是实际为负却判为正；漏报是实际为正却判为负。正例代表什么，要先按任务定义。',
        'metrics',
        ['confusion-matrix'],
        '自拟例：把正常设备判故障是误报；漏掉真实故障是漏报。',
      ),
      t(
        'roc-auc',
        'ROC 曲线下面积',
        'ROC AUC',
        '综合不同阈值下真正率与假正率的关系，衡量二分类模型区分正负样本的能力。',
        'scoring',
        ['accuracy', 'calibration'],
      ),
      t(
        'rmse',
        '均方根误差',
        'Root Mean Squared Error · RMSE',
        '预测误差先平方、求平均再开方；结果与目标变量同单位，对较大误差更敏感。',
        'scoring',
        ['regression', 'r-squared'],
      ),
      t(
        'r-squared',
        '决定系数',
        'R-squared · R²',
        '相对于用观测目标均值作预测的基准，描述回归预测拟合程度的评分；测试集上可以为负。',
        'scoring',
        ['rmse'],
        '在车辆侧碰案例中，R² 评价代理模型预测，不是直接评价解释质量。',
      ),
      t(
        'cross-validation',
        '交叉验证',
        'Cross-validation',
        '用多次训练／验证划分估计模型表现；划分方式应匹配独立样本、分组或时序等条件。',
        'crossvalidation',
        ['dataset-split'],
      ),
      t(
        'calibration',
        '概率校准',
        'Probability calibration',
        '预测概率与实际发生频率的吻合程度。',
        'calibration',
        ['uncertainty', 'trust'],
        '直觉例：许多被报为 80% 概率的事件中，约 80% 实际发生，才接近这一档的校准。',
      ),
      t(
        'uncertainty',
        '不确定性',
        'Uncertainty',
        '描述模型对结果或自身知识的不确定程度；可区分数据噪声相关与模型知识相关的不确定性。',
        'uncertainty',
        ['calibration'],
      ),
      t(
        'aleatoric-epistemic',
        '数据与认知不确定性',
        'Aleatoric / Epistemic uncertainty',
        '前者来自观测噪声等数据因素；后者与模型知识不足有关，通常可能通过增加相关数据减小。',
        'uncertainty',
        ['uncertainty'],
      ),
      t(
        'faithfulness',
        '忠实性',
        'Faithfulness / Fidelity',
        '解释与它所描述的模型行为或依据的对应程度。具体检验取决于解释对象与方法。',
        'p5',
        ['sanity-check', 'hallucination'],
      ),
      t(
        'stability',
        '解释稳定性',
        'Explanation stability',
        '在相近输入或可比条件下，解释是否发生不成比例的变化。研究时需要明确比较方式。',
        'p4',
        ['robustness'],
      ),
      t(
        'robustness',
        '稳健性／鲁棒性',
        'Robustness',
        '面对扰动、噪声或条件变化时，模型或解释能否维持所需性质。',
        'p4',
        ['stability'],
      ),
      t(
        'sanity-check',
        '合理性检查',
        'Sanity check',
        '用有辨别力的对照检查方法是否确实响应它应该依赖的信息，例如随机化模型参数后再看显著性图。',
        'p15',
        ['grad-cam', 'faithfulness'],
      ),
      t(
        'kendall-tau',
        '肯德尔秩相关',
        'Kendall’s tau',
        '通过比较样本对的排序一致与不一致情况，衡量两个排序的关联。',
        'kendall',
        ['rbo'],
      ),
      t(
        'rbo',
        '排序偏置重合度',
        'Rank-Biased Overlap · RBO',
        '比较排序列表的重合程度，可更重视前列，并处理不完全相同或不完整的列表。',
        'rbo',
        ['kendall-tau'],
      ),
      t(
        'ablation',
        '消融实验',
        'Ablation study',
        '移除或改变某个组件，再比较结果，以研究该组件在系统中的作用。',
        'p18',
        ['intervention'],
      ),
    ],
  },
  {
    id: 'operations',
    zh: '从模型到真实产品',
    en: 'MLOps & deployment',
    intro: '上线以后，数据、模型和使用情境还会继续变化。',
    terms: [
      t(
        'mlops',
        '机器学习运维',
        'Machine Learning Operations · MLOps',
        '把模型开发与持续运行连接起来的工程实践，包括数据、训练、测试、部署、监测与更新。',
        'mlops',
        ['pipeline', 'monitoring'],
        '对设计者，关键是知道：谁发现失效、谁能更新、更新后哪些行为需要重新解释。此句为应用提示。',
      ),
      t(
        'pipeline',
        '流水线',
        'ML pipeline',
        '把数据处理、训练、验证与部署等步骤连接成可重复运行的过程。',
        'mlops',
        ['mlops', 'ci-cd-ct'],
      ),
      t(
        'ci-cd-ct',
        '集成、交付与持续训练',
        'CI / CD / CT',
        'CI 自动检查集成变更；CD 支持经过验证的版本交付；CT 在需要时触发重新训练。',
        'mlops',
        ['pipeline'],
      ),
      t(
        'deployment',
        '模型部署',
        'Model deployment / Serving',
        '把模型放入可被应用调用的运行环境，使它能够实际处理请求。',
        'mlops',
        ['inference', 'monitoring'],
      ),
      t(
        'monitoring',
        '运行监测',
        'Monitoring',
        '持续观察数据、模型表现、运行状态与真实使用指标，以发现变化和问题。',
        'monitoring',
        ['data-drift', 'training-serving-skew'],
      ),
      t(
        'data-drift',
        '数据漂移',
        'Data drift',
        '当前输入数据的分布相对参考数据发生变化。变化是检查信号，不必然意味着任务表现已经下降。',
        'drift',
        ['monitoring', 'generalization'],
        '自拟例：换了一种包装材料后，机器人摄像头输入的颜色与反光分布发生变化。',
      ),
      t(
        'training-serving-skew',
        '训练与服务偏差',
        'Training-serving skew',
        '训练阶段和实际服务阶段的数据、特征或处理方式不一致。',
        'monitoring',
        ['data-leakage', 'data-drift'],
      ),
      t(
        'experiment-tracking',
        '实验跟踪',
        'Experiment tracking',
        '记录一次训练或评估所用参数、指标和产物，方便比较、追溯和复现。',
        'tracking',
        ['model-registry'],
      ),
      t(
        'model-registry',
        '模型注册表',
        'Model registry',
        '集中管理模型版本、元数据及生命周期信息的目录或服务。',
        'registry',
        ['experiment-tracking', 'model-card'],
      ),
      t(
        'model-card',
        '模型卡',
        'Model card',
        '记录模型用途、评估条件、性能和限制等信息的结构化说明。',
        'modelcard',
        ['datasheet', 'mlops'],
      ),
      t(
        'datasheet',
        '数据说明书',
        'Datasheet for dataset',
        '记录数据集的动机、构成、收集过程、用途及维护情况的文档。',
        'datasheet',
        ['dataset', 'model-card'],
      ),
      t(
        'latency',
        '延迟',
        'Latency',
        '从发起请求到收到响应的耗时；应明确测量范围，如模型计算或端到端交互。',
        'monitoring',
        ['deployment'],
        '自拟例：语音提示要等两秒才响起，是否错过了协作动作的时机？',
      ),
    ],
  },
  {
    id: 'human',
    zh: '人、交互与具身情境',
    en: 'People & interaction',
    intro: '这些词在不同学科中有不同用法，以下按本指南的研究语境解释。',
    terms: [
      t(
        'human-ai',
        '人机交互／人智交互',
        'HCI / Human–AI Interaction',
        'HCI 研究人与计算系统的交互；Human–AI Interaction 更聚焦具有 AI 能力、会预测或生成的系统。',
        'hai',
        ['mental-model', 'agency'],
      ),
      t(
        'mental-model',
        '心智模型',
        'Mental model',
        '使用者对系统如何工作形成的内部理解，它影响预期、解释与行动。',
        'p3',
        ['understanding', 'predictability'],
      ),
      t(
        'explanation-needs',
        '解释需求',
        'Explanation needs',
        '人在任务中需要通过解释回答的问题，例如为什么选择它、为什么不是另一个、怎样改变结果。',
        'p3',
        ['contrastive', 'explanation'],
      ),
      t(
        'contrastive',
        '对比性解释',
        'Contrastive explanation',
        '围绕“为什么是这个，而不是那个”提供解释；用户预想的替代结果是理解问题的重要线索。',
        'p2',
        ['explanation-needs'],
      ),
      t(
        'trust',
        '信任',
        'Trust',
        '使用者对系统能力、行为或可靠性形成的态度；它与实际采纳行为有关，但不是同一个测量对象。',
        'p14',
        ['appropriate-reliance', 'calibration'],
      ),
      t(
        'appropriate-reliance',
        '适当依赖',
        'Appropriate reliance',
        '根据系统在当前情境中的能力与限制，作出合适的采纳、拒绝或核查选择。',
        'p14',
        ['trust', 'understanding'],
      ),
      t(
        'understanding',
        '理解',
        'Understanding / Comprehension',
        '用户能否形成足以支持当前任务的认识；可通过复述、预测新案例和实际表现等方式研究。',
        'p14',
        ['mental-model', 'task-performance'],
      ),
      t(
        'agency',
        '能动性',
        'Human agency',
        '人在交互中形成意图、作出选择并影响结果的能力与空间；此处关注纠正、拒绝与控制等可实施操作。',
        'hai',
        ['actionability', 'human-in-loop'],
      ),
      t(
        'human-in-loop',
        '人在回路中',
        'Human-in-the-loop · HITL',
        '让人参与系统某些关键环节，例如标注、复核、纠正或决定是否执行；具体参与点需要说明。',
        'hai',
        ['agency'],
      ),
      t(
        'legibility',
        '意图可读性',
        'Legibility',
        '从已经观察到的动作推断智能体目标的容易程度。',
        'p12',
        ['predictability', 'embodied-cues'],
      ),
      t(
        'predictability',
        '可预测性',
        'Predictability',
        '在知道目标或情境时，系统后续行为是否符合观察者的预期。',
        'p12',
        ['legibility', 'mental-model'],
      ),
      t(
        'embodied-cues',
        '具身／社会线索',
        'Embodied / Social cues',
        '通过注视、姿态、手势、运动等可感知行为传达状态或意图的线索。',
        'p11',
        ['legibility'],
      ),
      t(
        'workload',
        '主观工作负荷',
        'Subjective workload',
        '人感受到的任务负担，可涉及心理、身体、时间、努力与挫败等维度。',
        'tlx',
        ['nasa-tlx'],
      ),
      t(
        'nasa-tlx',
        'NASA 任务负荷指数',
        'NASA Task Load Index · NASA-TLX',
        '评估主观工作负荷的工具，包含心理、身体、时间需求，表现、努力与挫败六个维度。',
        'tlx',
        ['workload'],
      ),
      t(
        'task-performance',
        '任务表现',
        'Task performance',
        '在具体任务中的完成质量、错误、用时等表现；指标应对应研究希望支持的行为。',
        'p20',
        ['understanding', 'appropriate-reliance'],
      ),
    ],
  },
];
export const allTerms = glossaryGroups.flatMap((group) => group.terms);
export const termById = Object.fromEntries(
  allTerms.map((term) => [term.id, term]),
);
