export const sources = [
  {
    id: 1,
    author: 'Ali et al.',
    year: '2023',
    title:
      'Explainable Artificial Intelligence (XAI): What we know and what is left to attain Trustworthy Artificial Intelligence',
    venue: 'Information Fusion 99 · 101805',
    url: 'https://doi.org/10.1016/j.inffus.2023.101805',
    type: '综述 Review',
    use: '领域总览与可信 AI。',
  },
  {
    id: 2,
    author: 'Miller',
    year: '2019',
    title:
      'Explanation in artificial intelligence: Insights from the social sciences',
    venue: 'Artificial Intelligence 267 · 1–38',
    url: 'https://doi.org/10.1016/j.artint.2018.07.007',
    type: '综述 Review',
    use: '人的解释需求与社会科学。',
  },
  {
    id: 3,
    author: 'Liao, Gruen & Miller',
    year: '2020',
    title:
      'Questioning the AI: Informing Design Practices for Explainable AI User Experiences',
    venue: 'CHI 2020',
    url: 'https://doi.org/10.1145/3313831.3376590',
    type: '实证研究 Empirical',
    use: '20 位 UX／设计从业者访谈与用户问题库。',
  },
  {
    id: 4,
    author: 'Sokol & Flach',
    year: '2020',
    title:
      'Explainability Fact Sheets: A Framework for Systematic Assessment of Explainable Approaches',
    venue: 'FAT* 2020 · 56–67',
    url: 'https://doi.org/10.1145/3351095.3372870',
    type: '框架 Framework',
    use: '功能、运行、可用性、安全与验证。',
  },
  {
    id: 5,
    author: 'Phillips et al. / NIST',
    year: '2021',
    title: 'Four Principles of Explainable Artificial Intelligence',
    venue: 'NISTIR 8312',
    url: 'https://doi.org/10.6028/NIST.IR.8312',
    type: '技术报告 Report',
    use: '解释、有意义、解释准确性、知识边界。',
  },
  {
    id: 6,
    author: 'Lundberg & Lee',
    year: '2017',
    title: 'A Unified Approach to Interpreting Model Predictions',
    venue: 'NeurIPS 2017',
    url: 'https://proceedings.neurips.cc/paper_files/paper/2017/hash/8a20a8621978632d76c43dfd28b67767-Abstract.html',
    type: '方法 Method',
    use: 'SHAP 特征归因。',
  },
  {
    id: 7,
    author: 'Ribeiro, Singh & Guestrin',
    year: '2016',
    title:
      '“Why Should I Trust You?”: Explaining the Predictions of Any Classifier',
    venue: 'KDD 2016',
    url: 'https://arxiv.org/abs/1602.04938',
    type: '方法与实验 Method + study',
    use: 'LIME 局部解释与模型排错。',
  },
  {
    id: 8,
    author: 'Mothilal, Sharma & Tan',
    year: '2020',
    title:
      'Explaining Machine Learning Classifiers through Diverse Counterfactual Explanations',
    venue: 'FAT* 2020',
    url: 'https://doi.org/10.1145/3351095.3372850',
    type: '方法 Method',
    use: 'DiCE；反事实多样性与可行性。',
  },
  {
    id: 9,
    author: 'Kim et al.',
    year: '2018',
    title:
      'Interpretability Beyond Feature Attribution: Quantitative Testing with Concept Activation Vectors (TCAV)',
    venue: 'ICML 2018',
    url: 'https://proceedings.mlr.press/v80/kim18d.html',
    type: '方法 Method',
    use: '用户定义概念与模型敏感性。',
  },
  {
    id: 10,
    author: 'Koh et al.',
    year: '2020',
    title: 'Concept Bottleneck Models',
    venue: 'ICML 2020 · PMLR 119',
    url: 'https://proceedings.mlr.press/v119/koh20a.html',
    type: '方法与实验 Method + study',
    use: '鸟类识别、X 光评级与概念干预。',
  },
  {
    id: 11,
    author: 'Wallkötter et al.',
    year: '2021',
    title: 'Explainable Embodied Agents Through Social Cues: A Review',
    venue: 'ACM THRI 10(3) · Article 27',
    url: 'https://doi.org/10.1145/3457188',
    type: '综述 Review',
    use: '社会线索与具身解释。',
  },
  {
    id: 12,
    author: 'Dragan, Lee & Srinivasa',
    year: '2013',
    title: 'Legibility and Predictability of Robot Motion',
    venue: 'ACM/IEEE HRI 2013',
    url: 'https://personalrobotics.cs.washington.edu/publications/dragan2013legibility.pdf',
    type: '实证研究 Empirical',
    use: '意图可读性与动作可预测性。',
  },
  {
    id: 13,
    author: 'Alvanpour et al.',
    year: '2025',
    title:
      'Comparative Analysis of Post Hoc Explainable Methods for Robotic Grasp Failure Prediction',
    venue: 'Electronics 14(9) · 1868',
    url: 'https://doi.org/10.3390/electronics14091868',
    type: '比较研究 Comparative',
    use: '模拟抓取数据与三种解释方法。访问说明：依据可检索摘要与元数据，全文访问受限。',
  },
  {
    id: 14,
    author: 'Rong et al.',
    year: '2024',
    title:
      'Towards Human-Centered Explainable AI: A Survey of User Studies for Model Explanations',
    venue: 'IEEE TPAMI 46(4) · 2104–2122',
    url: 'https://doi.org/10.1109/TPAMI.2023.3331846',
    type: '综述 Review',
    use: '97 篇核心论文；理解、信任、可用性与协作评估。',
  },
  {
    id: 15,
    author: 'Adebayo et al.',
    year: '2018',
    title: 'Sanity Checks for Saliency Maps',
    venue: 'NeurIPS 2018',
    url: 'https://arxiv.org/abs/1810.03292',
    type: '验证研究 Validation',
    use: '检查显著性图对模型参数与数据的依赖。',
  },
  {
    id: 16,
    author: 'Rudin',
    year: '2019',
    title:
      'Stop explaining black box machine learning models for high stakes decisions and use interpretable models instead',
    venue: 'Nature Machine Intelligence 1 · 206–215',
    url: 'https://doi.org/10.1038/s42256-019-0048-x',
    type: '立场论文 Perspective',
    use: '先检验可解释模型是否足够。',
  },
  {
    id: 17,
    author: 'Fiok et al.',
    year: '2022 / online 2021',
    title: 'Explainable artificial intelligence for education and training',
    venue: 'Journal of Defense Modeling and Simulation 19(2) · 133–144',
    url: 'https://doi.org/10.1177/15485129211028651',
    type: '综述 Review',
    use: '教育与培训中的解释需求；依据摘要，未声称全文精读。',
  },
  {
    id: 18,
    author: 'Lindsey et al.',
    year: '2025',
    title: 'On the Biology of a Large Language Model',
    venue: 'Transformer Circuits · research publication',
    url: 'https://transformer-circuits.pub/2025/attribution-graphs/biology.html',
    type: '研究报告 Research report',
    use: 'Claude 3.5 Haiku 的归因图与干预研究。',
  },
  {
    id: 19,
    author: 'Anthropic Alignment Science',
    year: '2025',
    title: 'Reasoning Models Don’t Always Say What They Think',
    venue: '原始研究介绍与论文入口',
    url: 'https://www.anthropic.com/research/reasoning-models-dont-say-think',
    type: '研究报告 Research report',
    use: '思维链文字理由的忠实性。',
  },
  {
    id: 20,
    author: 'Doshi-Velez & Kim',
    year: '2017',
    title: 'Towards A Rigorous Science of Interpretable Machine Learning',
    venue: 'arXiv · position paper',
    url: 'https://arxiv.org/abs/1702.08608',
    type: '立场与框架 Perspective',
    use: '应用、人类与功能层面的解释评估。',
  },
  {
    id: 21,
    author: 'Selvaraju et al.',
    year: '2017',
    title:
      'Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization',
    venue: 'ICCV 2017',
    url: 'https://arxiv.org/abs/1610.02391',
    type: '方法 Method',
    use: '梯度加权的类别相关区域定位。',
  },
  {
    id: 22,
    author: 'Ando Saabas',
    year: '软件文档',
    title: 'TreeInterpreter',
    venue: '作者维护的 GitHub 仓库',
    url: 'https://github.com/andosa/treeinterpreter',
    type: '软件文档 Software',
    use: '支持的 sklearn 树模型、安装与预测分解接口。',
  },
  {
    id: 23,
    author: 'Ando Saabas',
    year: '2014',
    title: 'Interpreting random forests',
    venue: '作者技术文章 · DataDive',
    url: 'https://blog.datadive.net/interpreting-random-forests/',
    type: '作者说明 Technical article',
    use: '沿树路径累积特征贡献的直观推导；不是同行评审论文。',
  },
  {
    id: 24,
    author: 'Hsu, Wu & Liu',
    year: '2024',
    title:
      'Decoding AI Complexity: SHAP Textual Explanations via LLM for Improved Model Transparency',
    venue: 'ICCE-Taiwan 2024 · 197–198',
    url: 'https://doi.org/10.1109/ICCE-Taiwan62264.2024.10674465',
    type: '会议论文 Conference',
    use: '原笔记中的 SHAP + LLM 示例。已核对书目信息；具体操作链依据用户提供的流程笔记，未重新核验全文。',
  },
  {
    id: 25,
    author: 'Mathieu et al.',
    year: '2025',
    title:
      'Enhancing numerical simulation analysis with the use of explainable artificial intelligence and large language models: a case study on vehicle side crash optimization',
    venue: 'Proceedings of the Design Society 5 · ICED25',
    url: 'https://doi.org/10.1017/pds.2025.10168',
    type: '工程案例 Engineering case',
    use: '车辆侧碰：有限元、代理模型、TreeSHAP 与 LLM。正文数据来自原论文，设计延伸另行标注。',
  },
  {
    id: 26,
    author: 'Lundberg et al.',
    year: '2020',
    title:
      'From local explanations to global understanding with explainable AI for trees',
    venue: 'Nature Machine Intelligence 2',
    url: 'https://www.nature.com/articles/s42256-019-0138-9',
    type: '方法 Method',
    use: 'TreeSHAP 与从单个样本到整体模型的解释。',
  },
  {
    id: 27,
    author: 'Zhao et al.',
    year: '2024',
    title: 'Explainability for Large Language Models: A Survey',
    venue: 'ACM Transactions on Intelligent Systems and Technology',
    url: 'https://doi.org/10.1145/3639372',
    type: '综述 Review',
    use: 'LLM 可解释性的对象、方法与评估入口。',
  },
];
